## Basics of NLP

In [11]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords



In [10]:

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
sample_text = "Natural Language Processing (NLP) is a fascinating field. It enables computers to understand, interpret, and generate human language. Researchers are constantly improving these algorithms, leading to breakthroughs like large language models."

# 1. Tokenization
# Tokenization is the process of breaking down a text into smaller units, such as words or sentences.
# We'll use word_tokenize from NLTK to split the text into individual words.
words = word_tokenize(sample_text.lower()) # Convert to lowercase for consistent processing
print(f"Original Text: {sample_text}\n")
print(f"Tokenized Words: {words}\n")

# 2. Stemming
# Stemming is the process of reducing inflected (or sometimes derived) words to their word stem, base or root form.
# It's a heuristic process that often cuts off the end or beginning of the word.
porter_stemmer = PorterStemmer()
stemmed_words = [porter_stemmer.stem(word) for word in words]
print(f"Stemmed Words (Porter Stemmer):\n")
for original, stemmed in zip(words, stemmed_words):
    print(f"  '{original}' -> '{stemmed}'")
print("\nNote: Stemming is a crude heuristic process. 'Processing' becomes 'process', 'fascinating' becomes 'fascin', 'improving' becomes 'improv'.")
print("\n")

# 3. Lemmatization
# Lemmatization is the process of reducing inflected words to their base or root form, also known as the lemma.
# Unlike stemming, lemmatization uses vocabulary and morphological analysis to return a valid word from the dictionary.
wordnet_lemmatizer = WordNetLemmatizer()
lemmatized_words = [wordnet_lemmatizer.lemmatize(word) for word in words]
print(f"Lemmatized Words (WordNetLemmatizer):\n")
for original, lemmatized in zip(words, lemmatized_words):
    print(f"  '{original}' -> '{lemmatized}'")
print("\nNote: Lemmatization is more sophisticated than stemming. 'Processing' becomes 'processing' (requires POS tag for verb), 'fascinating' becomes 'fascinating', 'improving' becomes 'improving'.")
print("To get better lemmatization, Part-of-Speech (POS) tagging is often used, as 'processing' as a noun is different from 'processing' as a verb.")
print("\n")

# 4. Stop Word Removal
# Stop words are common words (like 'the', 'is', 'a') that often carry little significant meaning in text analysis.
# Removing them can help reduce noise and focus on more important terms.
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word not in stop_words and word.isalpha()]
print(f"Words before Stop Word Removal: {words}\n")
print(f"Words after Stop Word Removal: {filtered_words}\n")
print("Note: We also removed punctuation by checking if the word consists only of alphabetic characters.")


Original Text: Natural Language Processing (NLP) is a fascinating field. It enables computers to understand, interpret, and generate human language. Researchers are constantly improving these algorithms, leading to breakthroughs like large language models.

Tokenized Words: ['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'fascinating', 'field', '.', 'it', 'enables', 'computers', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'researchers', 'are', 'constantly', 'improving', 'these', 'algorithms', ',', 'leading', 'to', 'breakthroughs', 'like', 'large', 'language', 'models', '.']

Stemmed Words (Porter Stemmer):

  'natural' -> 'natur'
  'language' -> 'languag'
  'processing' -> 'process'
  '(' -> '('
  'nlp' -> 'nlp'
  ')' -> ')'
  'is' -> 'is'
  'a' -> 'a'
  'fascinating' -> 'fascin'
  'field' -> 'field'
  '.' -> '.'
  'it' -> 'it'
  'enables' -> 'enabl'
  'computers' -> 'comput'
  'to' -> 'to'
  'understand' -> 'understand'
  '

In [13]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Download additional necessary NLTK data identified from the error traceback
nltk.download('punkt_tab', quiet=True)

sample_text = "Natural Language Processing (NLP) is a fascinating field. It enables computers to understand, interpret, and generate human language. Researchers are constantly improving these algorithms, leading to breakthroughs like large language models."

# 1. Tokenization
# Tokenization is the process of breaking down a text into smaller units, such as words or sentences.
# We'll use word_tokenize from NLTK to split the text into individual words.
words = word_tokenize(sample_text.lower()) # Convert to lowercase for consistent processing
print(f"Original Text: {sample_text}\n")
print(f"Tokenized Words: {words}\n")

# 2. Stemming
# Stemming is the process of reducing inflected (or sometimes derived) words to their word stem, base or root form.
# It's a heuristic process that often cuts off the end or beginning of the word.
porter_stemmer = PorterStemmer()
stemmed_words = [porter_stemmer.stem(word) for word in words]
print(f"Stemmed Words (Porter Stemmer):\n")
for original, stemmed in zip(words, stemmed_words):
    print(f"  '{original}' -> '{stemmed}'")
print("\nNote: Stemming is a crude heuristic process. 'Processing' becomes 'process', 'fascinating' becomes 'fascin', 'improving' becomes 'improv'.")
print("\n")

# 3. Lemmatization
# Lemmatization is the process of reducing inflected words to their base or root form, also known as the lemma.
# Unlike stemming, lemmatization uses vocabulary and morphological analysis to return a valid word from the dictionary.
wordnet_lemmatizer = WordNetLemmatizer()
lemmatized_words = [wordnet_lemmatizer.lemmatize(word) for word in words]
print(f"Lemmatized Words (WordNetLemmatizer):\n")
for original, lemmatized in zip(words, lemmatized_words):
    print(f"  '{original}' -> '{lemmatized}'")
print("\nNote: Lemmatization is more sophisticated than stemming. 'Processing' becomes 'processing' (requires POS tag for verb), 'fascinating' becomes 'fascinating', 'improving' becomes 'improving'.")
print("To get better lemmatization, Part-of-Speech (POS) tagging is often used, as 'processing' as a noun is different from 'processing' as a verb.")
print("\n")

# 4. Stop Word Removal
# Stop words are common words (like 'the', 'is', 'a') that often carry little significant meaning in text analysis.
# Removing them can help reduce noise and focus on more important terms.
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word not in stop_words and word.isalpha()]
print(f"Words before Stop Word Removal: {words}\n")
print(f"Words after Stop Word Removal: {filtered_words}\n")
print("Note: We also removed punctuation by checking if the word consists only of alphabetic characters.")

Original Text: Natural Language Processing (NLP) is a fascinating field. It enables computers to understand, interpret, and generate human language. Researchers are constantly improving these algorithms, leading to breakthroughs like large language models.

Tokenized Words: ['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'fascinating', 'field', '.', 'it', 'enables', 'computers', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'researchers', 'are', 'constantly', 'improving', 'these', 'algorithms', ',', 'leading', 'to', 'breakthroughs', 'like', 'large', 'language', 'models', '.']

Stemmed Words (Porter Stemmer):

  'natural' -> 'natur'
  'language' -> 'languag'
  'processing' -> 'process'
  '(' -> '('
  'nlp' -> 'nlp'
  ')' -> ')'
  'is' -> 'is'
  'a' -> 'a'
  'fascinating' -> 'fascin'
  'field' -> 'field'
  '.' -> '.'
  'it' -> 'it'
  'enables' -> 'enabl'
  'computers' -> 'comput'
  'to' -> 'to'
  'understand' -> 'understand'
  '

In [14]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 1. Define a small corpus of sample documents
corpus = [
    "NLP is a fascinating field of AI",
    "AI and Machine Learning are revolutionizing industries",
    "Natural Language Processing is key to understanding human language",
    "Deep Learning models power advanced NLP applications"
]

print("Sample Corpus:")
for i, doc in enumerate(corpus):
    print(f"Document {i+1}: {doc}")
print("\n")

# 3. For Bag-of-Words (BoW):
# BoW represents text as the bag (multiset) of its words, disregarding grammar and even word order
# but keeping multiplicity. It focuses on the occurrence of words within a document.

# a. Instantiate CountVectorizer
cv_vectorizer = CountVectorizer()

# b. Fit the vectorizer to your corpus and transform the corpus into a BoW matrix
bow_matrix = cv_vectorizer.fit_transform(corpus)

# c. Print the vocabulary learned by the CountVectorizer
feature_names_bow = cv_vectorizer.get_feature_names_out()
print("Bag-of-Words (BoW) Vocabulary (Features):")
print(feature_names_bow)
print("\n")

# d. Print the bow_matrix and explain what the numbers represent.
print("Bag-of-Words Matrix:")
bow_array = bow_matrix.toarray()
print(bow_array)
print("\nExplanation of BoW Matrix:")
print("Each row in the matrix corresponds to a document in the corpus.")
print("Each column corresponds to a unique word in the vocabulary (feature_names_bow).")
print("The value in each cell represents the frequency (count) of that specific word in that specific document.")
print("For example, if 'nlp' is the 7th word in the vocabulary (index 6) and the first document is [1 0 0 ... 1 ...], it means 'nlp' appears once in the first document.")

Sample Corpus:
Document 1: NLP is a fascinating field of AI
Document 2: AI and Machine Learning are revolutionizing industries
Document 3: Natural Language Processing is key to understanding human language
Document 4: Deep Learning models power advanced NLP applications


Bag-of-Words (BoW) Vocabulary (Features):
['advanced' 'ai' 'and' 'applications' 'are' 'deep' 'fascinating' 'field'
 'human' 'industries' 'is' 'key' 'language' 'learning' 'machine' 'models'
 'natural' 'nlp' 'of' 'power' 'processing' 'revolutionizing' 'to'
 'understanding']


Bag-of-Words Matrix:
[[0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 1 2 0 0 0 1 0 0 0 1 0 1 1]
 [1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0]]

Explanation of BoW Matrix:
Each row in the matrix corresponds to a document in the corpus.
Each column corresponds to a unique word in the vocabulary (feature_names_bow).
The value in each cell represents the frequency (count

In [15]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 1. Define a small corpus of sample documents (re-defining for clarity, though it's already in scope)
corpus = [
    "NLP is a fascinating field of AI",
    "AI and Machine Learning are revolutionizing industries",
    "Natural Language Processing is key to understanding human language",
    "Deep Learning models power advanced NLP applications"
]

# 4. For TF-IDF:
# TF-IDF (Term Frequency-Inverse Document Frequency) is a numerical statistic that is intended to reflect
# how important a word is to a document in a collection or corpus. It increases proportionally to the
# number of times a word appears in the document but is offset by the frequency of the word in the corpus,
# which helps to adjust for the fact that some words appear more frequently in general.

# a. Instantiate TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# b. Fit the vectorizer to your corpus and transform the corpus into a TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

# c. Print the vocabulary learned by the TfidfVectorizer
feature_names_tfidf = tfidf_vectorizer.get_feature_names_out()
print("\nTerm Frequency-Inverse Document Frequency (TF-IDF) Vocabulary (Features):")
print(feature_names_tfidf)
print("\n")

# d. Print the tfidf_matrix and explain what the numbers represent, contrasting them with BoW.
print("TF-IDF Matrix:")
tfidf_array = tfidf_matrix.toarray()
print(np.round(tfidf_array, 2)) # Round for better readability
print("\nExplanation of TF-IDF Matrix:")
print("Each row in the matrix corresponds to a document, and each column corresponds to a unique word (feature).")
print("The values in this matrix are TF-IDF scores, which are a product of two terms:")
print("  - Term Frequency (TF): How often a word appears in a document.")
print("  - Inverse Document Frequency (IDF): A measure of how rare or common a word is across the entire corpus.")
print("Words that are common within a document but rare across the entire corpus will have higher TF-IDF scores (e.g., 'nlp', 'fascinating', 'revolutionizing').")
print("Conversely, common words (like 'is', 'a', 'of', if not removed) that appear in many documents will have lower TF-IDF scores because their IDF value is low, signifying less unique information provided.")
print("Unlike BoW, which only gives raw counts, TF-IDF gives a weighted score, emphasizing words that are more important to a specific document relative to the entire corpus.")



Term Frequency-Inverse Document Frequency (TF-IDF) Vocabulary (Features):
['advanced' 'ai' 'and' 'applications' 'are' 'deep' 'fascinating' 'field'
 'human' 'industries' 'is' 'key' 'language' 'learning' 'machine' 'models'
 'natural' 'nlp' 'of' 'power' 'processing' 'revolutionizing' 'to'
 'understanding']


TF-IDF Matrix:
[[0.   0.36 0.   0.   0.   0.   0.45 0.45 0.   0.   0.36 0.   0.   0.
  0.   0.   0.   0.36 0.45 0.   0.   0.   0.   0.  ]
 [0.   0.32 0.4  0.   0.4  0.   0.   0.   0.   0.4  0.   0.   0.   0.32
  0.4  0.   0.   0.   0.   0.   0.   0.4  0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.31 0.   0.24 0.31 0.61 0.
  0.   0.   0.31 0.   0.   0.   0.31 0.   0.31 0.31]
 [0.4  0.   0.   0.4  0.   0.4  0.   0.   0.   0.   0.   0.   0.   0.32
  0.   0.4  0.   0.32 0.   0.4  0.   0.   0.   0.  ]]

Explanation of TF-IDF Matrix:
Each row in the matrix corresponds to a document, and each column corresponds to a unique word (feature).
The values in this matrix are TF-IDF scores

In [16]:
import pandas as pd

# Sample dataset for sentiment analysis
data = {
    'text': [
        "This is an amazing product! I love it.",
        "The service was terrible and the food was cold.",
        "Highly recommend, excellent experience.",
        "Never buying this again. Complete waste of money.",
        "Good quality, happy with the purchase.",
        "Disappointing, expected much better.",
        "Fantastic performance, very impressed.",
        "Worst movie ever, don't watch it.",
        "Decent for the price, no complaints.",
        "Absolutely wonderful!"
    ],
    'sentiment': [
        'positive', 'negative', 'positive', 'negative', 'positive',
        'negative', 'positive', 'negative', 'positive', 'positive'
    ]
}

df = pd.DataFrame(data)
print("Sample Dataset:")
print(df)

# Separate text and labels
texts = df['text'].tolist()
labels = df['sentiment'].tolist()

print(f"\nNumber of texts: {len(texts)}")
print(f"Number of labels: {len(labels)}")

Sample Dataset:
                                                text sentiment
0             This is an amazing product! I love it.  positive
1    The service was terrible and the food was cold.  negative
2            Highly recommend, excellent experience.  positive
3  Never buying this again. Complete waste of money.  negative
4             Good quality, happy with the purchase.  positive
5               Disappointing, expected much better.  negative
6             Fantastic performance, very impressed.  positive
7                  Worst movie ever, don't watch it.  negative
8               Decent for the price, no complaints.  positive
9                              Absolutely wonderful!  positive

Number of texts: 10
Number of labels: 10


In [17]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Ensure NLTK data is downloaded (if not already handled in previous cells)
nltk.download('punkt', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True) # Explicitly download if needed, based on past errors

# Initialize stemmer, lemmatizer, and stopwords outside the function for efficiency
porter_stemmer = PorterStemmer()
wordnet_lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # 1. Convert to lowercase
    text = text.lower()

    # 2. Tokenization (word_tokenize automatically handles most punctuation)
    words = word_tokenize(text)

    # 3. Remove punctuation and non-alphabetic tokens, then remove stop words
    filtered_words = [word for word in words if word.isalpha() and word not in stop_words]

    # 4. Lemmatization (using WordNetLemmatizer)
    # Note: For better lemmatization, POS tagging is usually needed, but for simplicity here,
    # we're applying it without POS tags, which defaults to noun.
    lemmatized_words = [wordnet_lemmatizer.lemmatize(word) for word in filtered_words]

    # Optionally, you can also include stemming here, but usually one is chosen over the other.
    # For this example, we'll stick to lemmatization as it's generally more accurate.

    return " ".join(lemmatized_words)

# Apply preprocessing to each text in the dataset
preprocessed_texts = [preprocess_text(text) for text in texts]

print("Original Texts (first 3):")
for i in range(min(3, len(texts))):
    print(f"  - {texts[i]}")

print("\nPreprocessed Texts (first 3):")
for i in range(min(3, len(preprocessed_texts))):
    print(f"  - {preprocessed_texts[i]}")

print(f"\nTotal preprocessed texts: {len(preprocessed_texts)}")


Original Texts (first 3):
  - This is an amazing product! I love it.
  - The service was terrible and the food was cold.
  - Highly recommend, excellent experience.

Preprocessed Texts (first 3):
  - amazing product love
  - service terrible food cold
  - highly recommend excellent experience

Total preprocessed texts: 10


In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 3. Text Representation (Feature Engineering) using TF-IDF
# We'll use TF-IDF to convert the preprocessed text into numerical vectors.
# TF-IDF gives more weight to words that are important in a document but not too common across all documents.

tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer on the preprocessed texts and then transform them
X = tfidf_vectorizer.fit_transform(preprocessed_texts)

print("TF-IDF Feature Matrix created.")
print(f"Shape of TF-IDF feature matrix (documents x features): {X.shape}")
print(f"Number of unique features (words) extracted: {len(tfidf_vectorizer.get_feature_names_out())}")

# Display a small part of the vocabulary for inspection
print("\nSample of TF-IDF vocabulary (first 10 features):")
print(tfidf_vectorizer.get_feature_names_out()[:10])

TF-IDF Feature Matrix created.
Shape of TF-IDF feature matrix (documents x features): (10, 36)
Number of unique features (words) extracted: 36

Sample of TF-IDF vocabulary (first 10 features):
['absolutely' 'amazing' 'better' 'buying' 'cold' 'complaint' 'complete'
 'decent' 'disappointing' 'ever']
